DROP TABLE IF EXISTS CS_Users;

CREATE TABLE CS_Users
(
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	firstname VARCHAR(30) NOT NULL,
	lastname VARCHAR(30) NOT NULL,
	email VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	question VARCHAR(50) NOT NULL,
	answer VARCHAR(50) NOT NULL,
	quota BIGINT NOT NULL,
	salt MEDIUMINT NOT NULL,
	active TINYINT NOT NULL,
	rank VARCHAR(10) NOT NULL,
	reg_date TIMESTAMP
);