DROP TABLE IF EXISTS 'CS_Users';
DROP TABLE IF EXISTS 'CS_Files';

CREATE TABLE 'CS_Users'
(
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	firstname VARCHAR(30) NOT NULL,
	lastname VARCHAR(30) NOT NULL,
	email VARCHAR(50), NOT NULL,
	password VARCHAR(35) NOT NULL,
	question VARCHAR(50), NOT NULL,
	answer VARCHAR(35) NOT NULL,
	quota BIGINT,
	salt MEDIUMINT,
	avatar BLOB,
	active TINYINT,
	reg_date TIMESTAMP,
);